# Generated by Django 5.2.5 on 2025-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código corto único, p. ej. ARE, VDP.', max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del edificio.', max_length=120, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, help_text='Dirección completa.', max_length=200, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Baja'), ('under_construction', 'En construcción')], default='active', max_length=20, verbose_name='Estado')),
            ],
        ),
    ]
